djangoTopics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('topic.urls')),
]

topic/urls.py
from django.urls import path
from . import views

app_name = 'topic'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

topic/models.py
from django.db import models


class Topic(models.Model):

    class Meta:
        verbose_name = 'Заголовок'
        verbose_name_plural = 'Заголовки'

    name = models.TextField(max_length=200, verbose_name='Заголовок')
    created_at = models.DateTimeField(
        verbose_name='Создан',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name='Обновлен',
        auto_now=True
    )

    def __str__(self):
        return self.name


class Entry(models.Model):

    class Meta:
        verbose_name = 'Текст'
        verbose_name_plural = 'Тексты'

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='Заголовок')
    text = models.TextField(max_length=1000, verbose_name='Текст')
    created_at = models.DateTimeField(
        verbose_name='Создан',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name='Обновлен',
        auto_now=True
    )

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    phone_number = PhoneNumberField(verbose_name='Телефон', region='RU')

    objects = UserManager()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'phone_number', 'password1', 'password2']

topic/views.py
from django.shortcuts import render
from .models import Topic


def index(request):
    return render(request, 'index.html')


def topics(request):
    topics = Topic.objects.order_by('created_at')
    context = {'topics': topics}
    return render(request, 'topics.html', context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('created_at')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'topic.html', context)

users/views.py
import json
import urllib

from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings

from .forms import UserRegistrationForm


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''

            if result['success']:
                form.save()
                return redirect('users:login')
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        form = UserRegistrationForm()

    return render(request, 'registration/register.html', {'form': form})

templates/base.html
<p>
    <a href="{% url 'topic:index' %}">Главная</a>
    <a href="{% url 'topic:topics' %}">Новости</a>
    {% if user.is_authenticated %}
        Добро пожаловать, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'users:register' %}">Регистрация</a> -
        <a href="{% url 'users:login' %}">Войти</a>
    {% endif %}
</p>
{% block content %}{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Главная страница</h1>
    <p>Добро пожаловать на наш новостной дайджест!</p>
{% endblock content %}

templates/topic.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ topic }}</h1>
    <p>Содержание:</p>
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.created_at|date:'M d, Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
            </li>
        {% empty %}
            <li>К данному заголовку теста нет :(</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/topics.html
{% extends "base.html" %}
{% block content %}
<h1>Новости</h1>
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'topic:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
    <li>Пока новостей нет :(</li>
    {% endfor %}
</ul>
{% endblock content %}